# Generated by Django 4.1.1 on 2022-10-19 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telemart', '0002_remove_product_rating_product_power'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyMake',
            new_name='Company',
        ),
        migrations.AlterField(
            model_name='product',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='gpu_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
