# Generated by Django 4.1.1 on 2022-10-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemart', '0003_rename_companymake_company_alter_product_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.FileField(blank=True, null=True, upload_to='company_descriptions/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.FileField(blank=True, null=True, upload_to='product_descriptions/'),
        ),
    ]
