# Generated by Django 4.1.1 on 2022-10-20 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telemart', '0004_company_description_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='product_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
