# Generated by Django 4.1.1 on 2022-10-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemart', '0005_alter_product_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='official',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hotline',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
