# Generated by Django 4.1.1 on 2022-10-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemart', '0007_remove_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trailer',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
